<? include('templates/top.phtml');?>
    <div id="submenu">
        <h1>Aktualności</h1>
        <ul>
            <?if(!empty($t['menu'])): ?>
                <?$counter=0; foreach ($t['menu'] as $menu): ?>
                    <li>
                        <a class="submenu-left<?if($menu['id']==$t['record']['id']):?>-selected<?endif;?>" href="<?=SCRIPT."?category=$category&action=edit&id={$menu['id']}"?>"><?=$menu['title']?></a>
                        <div class="submenu-right">
                            <?if($menu['active']):?>
                                <a href="<?=SCRIPT."?category=$category&action=turnOff&id_s={$menu['id']}&id={$t['record']['id']}"?>" class="turnon">Włączony</a>
                            <?else:?>
                                <a href="<?=SCRIPT."?category=$category&action=turnOn&id_s={$menu['id']}&id={$t['record']['id']}"?>" class="turnoff">Wyłączony</a>
                            <?endif;?>
                            <a href="<?=SCRIPT."?category=$category&action=delete&id_s={$menu['id']}&id={$t['record']['id']}"?>" class="delete" onClick="return confirm('Czy na pewno chcesz usunąć tego newsa?');">Usuń</a>

                        </div>
                    </li>
                <?$counter++; endforeach; ?>
            <?endif; ?>
            <li class="noborder">
                <a class="submenu-right" href="<?=SCRIPT."?category=$category&action=add"?>">+ Dodaj News</a>
            </li>
        </ul>
    </div>
    <div id="content">
        <form method="post" action="<?=SCRIPT."?category=$category&action={$t['action']}" ?>" enctype="multipart/form-data">
            <ul>
                <?if(!empty ($t['message'])):?>
                    <li class="bold red">
                        <?=$t['message']?>
                    </li>                
                <?endif;?>
                <li>
                    <span class="content-span">Data</span>
                    <input name="date" type="text" value="<?=$t['record']['date']?>" />
                </li>
                <li>
                    <span class="content-span">Tytuł</span>
                    <input name="title" type="text" value="<?=$t['record']['title']?>" />
                </li>
                <?php if($t['record']['image']): ?>
                    <li>
                        <span class="content-span">Zdjęcie:</span>
                        <input type="hidden" name="is_image" value="1" />
                        <div id="main-picture-container_small">
                            <img src="images/newsy/<?=$t['record']['name'] ?>.jpg" alt=""/>
                            <div class="content-img-top-a">
                                <a href="<?=SCRIPT."?category=$category&action=delete-image&id={$t['record']['id']}"?>" class="content-usun" onclick="return confirm('Czy na pewno chcesz usunąć to zdjęcie?');">Usuń</a>
                            </div>
                        </div>
                    </li>
                <?php else:?>
                    <li>
                        <span class="content-span">Zdjęcie:</span>
                        <input type="hidden" name="is_image" value="0" />
                        <input type="file" name="image" />
                    </li>
                <?php endif;?>
                <li>
                    <span class="content-span">Wstęp</span>
                    <input name="short_text1" type="text" value="<?=$t['record']['short_text1']?>" />
                </li>
                <li>
                    <span class="content-span">Krótki opis</span>
                    <textarea name="short_text2" cols="53" rows="8"><?=$t['record']['short_text2']?></textarea>
                </li>
                <li>
                    <span class="content-span">Opis</span>
                    <textarea name="long_text" cols="53" rows="8"><?=$t['record']['long_text']?></textarea>
                </li>
                <li class="noborder">
                    <div id="content-zapisz">
                        <input type="hidden" name="id" value="<?=$t['record']['id']?>" />
                        <input type="image" id="content-zapisz-button" src="images/cms/button-zapisz-zmiany.gif" />
                    </div>
                </li>
            </ul>
        </form>
    </div>
<? include('templates/bottom.phtml');?>