<? include('templates/top.phtml');?>
    <div id="submenu">
        <h1>Podstrony</h1>
        <ul>
            <?if(!empty($t['menu'])): ?>
                <?$counter=0; foreach ($t['menu'] as $menu): ?>
                    <li>
                        <a class="submenu-left<?if($menu['id']==$t['record']['id']):?>-selected<?endif;?> submenu-left-shorter" href="<?=SCRIPT."?category=$category&action=edit&id={$menu['id']}"?>"><?=$menu['name']?></a>
                    </li>
                <?$counter++; endforeach; ?>
            <?endif; ?>
        </ul>
    </div>
    <div id="content">
        <form method="post" action="<?=SCRIPT."?category=$category&action={$t['action']}" ?>" enctype="multipart/form-data">
            <ul>
                <?if(!empty ($t['message'])):?>
                    <li class="bold red">
                        <?=$t['message']?>
                    </li>                
                <?endif;?>
                <li>
                    <span class="content-span">Tytuł</span>
                    <strong><?=$t['record']['name']?></strong>
                </li>
                <li>
                    <span class="content-span">Opis</span>
                    <textarea name="text" cols="53" rows="24"><?=$t['record']['text']?></textarea>
                </li>
                <li class="noborder">
                    <div id="content-zapisz">
                        <input type="hidden" name="id" value="<?=$t['record']['id']?>" />
                        <input type="image" id="content-zapisz-button" src="images/cms/button-zapisz-zmiany.gif" />
                    </div>
                </li>
            </ul>
        </form>
    </div>
<? include('templates/bottom.phtml');?>