<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>BreakThru Studios</title>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<meta http-equiv="Content-Language" content="pl" />
	<meta name="Description" content="BreakThru Studios" />
	<meta name="keywords" content="BreakThru Studios" />
	<link type="text/css" rel="stylesheet" href="styles/style.css" />
        <link href="scripts/jquery/fancybox/jquery.fancybox-1.3.4.css" rel="stylesheet" type="text/css" media="screen" />
        <link href="http://vjs.zencdn.net/c/video-js.css" rel="stylesheet" />
        <script type="text/javascript" src="scripts/modernizr.custom.37797.js"></script> 
	      <script type="text/javascript" src="scripts/jquery/jquery.min.js"></script>
        <script type="text/javascript" src="//maps.googleapis.com/maps/api/js?sensor=false"></script>
        <script async defer src="https://maps.googleapis.com/maps/api/js?sensor=false&key=AIzaSyDOCLvyNP__qbMPhfckYSwqnjf0SwB5dFw&callback=initMap" type="text/javascript"></script>
        <script type="text/javascript" src="scripts/jquery/jquery-mousewheel-3.0.6/jquery.mousewheel.js"></script>        
        <script type="text/javascript" src="scripts/jquery/jquery.imagesloaded.min.js"></script>        
        <script type="text/javascript" src="scripts/jquery/detectmobilebrowser.js"></script>        
        <script type="text/javascript" src="scripts/jquery/jquery.form.js"></script>        
        <script type="text/javascript" src="scripts/jquery/jquery.easing.1.3.js"></script>        
        <script type="text/javascript" src="scripts/jquery/jquery.ba-dotimeout.min.js"></script>        
        <script type="text/javascript" src="scripts/jquery/fancybox/jquery.fancybox-1.3.4.pack.js"></script>        
        <script type="text/javascript" src="scripts/md5.js"></script>
        <script type="text/javascript" src="scripts/common.js"></script>
        <script type="text/javascript" src="scripts/jquery/parallax.js"></script>        
        <script src="scripts/video.js"></script>
        
</head>
<body>
    <div id="loading">
        <div id="loading-holder"></div>
    </div>
    <div id="top">
        <div id="top-inner">
            
        <a href="#" id="logo">Breakthru Studios</a>
        <div id="langs-en">
            <span>Język</span>
            <ul>
                <li id="li-lang-pl"><a class="active" href="polish.php">PL</a></li>
                <li id="li-lang-uk"><a href="index.php">UK</a></li>
            </ul>
        </div>
        </div>
    </div>
    <ul id="menu-left">
        <li id="ml-li-strona-glowna"><a class="active a-strona-glowna" href="#strona-glowna">Strona Główna</a></li>
        <li id="ml-li-zespol"><a href="#zespol" class="a-zespol">Zespół</a></li>
        <li id="ml-li-oferta"><a href="#oferta" class="a-oferta">Oferta</a></li>
        <li id="ml-li-realizacje"><a href="#realizacje" class="a-realizacje">Realizacje</a></li>
        <li id="ml-li-showreel"><a href="#showreel" class="a-showreel">Showreel</a></li>
        <li id="ml-li-aktualnosci"><a href="#aktualnosci" class="a-aktualnosci">Aktualności</a></li>
        <li id="ml-li-poprzedni"><a href="#" class="a-prev">Poprzedni</a></li>
        <li id="ml-li-nastepny"><a href="#" class="a-next">Następny</a></li>
    </ul>
    <div id="middle">
        
    <!-- Speed 7 right -->
    <div id="parallax-bg7">
        <img id="bg7-5" src="images/slide5/bgr2.png" alt=""/>
    </div>
               
    <!-- Speed 6 right -->
    <div id="parallax-bg6">
        <div id="bg6-2">
            <div id="s2-div2">
                <div id="s2-div2-bottom"></div>
                <div id="s2-div2-left">
                    <span><b>Rada <br />
                    Nadzorcza:</b></span>
                    <br /><br />
                    Sean Michael Bobbitt
                    Zbigniew Markowski

                    <div id="s2-div2-hr"></div>

                    <span><b>Współpracujący 
                    reżyserzy:</b></span>
                    <br /><br />
                    Dorota Kobiela <br />
                    Dino Athanassiou <br />
                    Paul Bolger <br />
                    Charles Peattie <br />
                    Magdalena  Osińska <br />
                    Leevi Lemently <br />
                    Magdalena  Bryll <br />
                    Magdalena Parszewska <br />
                    Salvador Maldonado, <br />
                    Marianella Maldonado
                </div>
                <div id="s2-div2-right">
                    <div class="s2-person" id="s2-person1">
                        <div class="s2-person-inner" style="height: 92px;">
                            Magdalena Bargieł<br />
                            Szef Sprzedaży i Relacji Biznesowych<br /><br />
                            <a href="mailto:magda@breakthrustudios.pl">magda@breakthrustudios.pl</a><br />
                            Tel. +48 668 685 415
                        </div>
                    </div>
                    <div class="s2-person" id="s2-person2">
                        <div class="s2-person-inner">
                            Hugh Welchman <br />
                            Dyrektor Zarządzający <br /><br /> 
                            <a href="mailto:hugh@breakthrustudios.pl">hugh@breakthrustudios.pl</a>
                        </div>
                    </div>
                    <div class="s2-person" id="s2-person3">
                        <div class="s2-person-inner" style="height: 78px;">
                            Tomasz Wochniak <br />
                            Szef IT i Cyfrowej Obróbki Obrazu <br /><br /> 
                            <a href="mailto:tomek@breakthrustudios.pl">tomek@breakthrustudios.pl</a>
                        </div>
                    </div>
                    <div class="s2-person" id="s2-person4">
                        <div class="s2-person-inner" style="height: 76px;">
                            Maja Grudzińska <br />
                            Szef Produkcji <br /><br />                             
                            <a href="mailto:maja@breakthrustudios.pl">maja@breakthrustudios.pl</a><br />
                            Tel. +48 696 839 939
                        </div>
                    </div>
                </div>
            </div>
        </div>    
        
        <div id="bg6-6">
            <img src="images/slide6/title.png" alt="" id="s6-img1" />
            <p id="s6-p1">                
                <span>15/04/2012</span><br />
                Cras quis augue quis justo consequat ullamcorper. Suspendisse lobortis ultricies orci, quis tempor eros convallis vel. Aliquam euismod metus ac risus ultrices. <br /><br />
                
                <span>12/04/2012</span><br />
                Suscipit a mattis eu, pellentesque ut eros. Morbi id interdum sapien. Sed adipiscing feugiat tortor in tempus. <br /><br />

                <span>10/04/2012</span><br />
                Cras quis augue quis justo consequat ullamcorper. Suspendisse lobortis ultricies orci, quis tempor eros convallis vel. Aliquam euismod metus ac risus ultrices.
            </p>
        </div>
        
    </div>
    <!-- Speed 5 left-right -->
    <div id="parallax-bg5">
        <div id="bg5-1-en">
            <img src="images/slide1/title.png" alt="Zapraszamy do współpracy" id="s1-img1" />
            <p id="s1-p1">                
                W BreakThru Studios  przeprowadzimy dla Ciebie konwersje obrazu (spotu reklamowego, filmu promocyjnego, etc.) <br />2D na stereo 3D, zrealizujemy obraz w stereo 3D, połączymy animację i zdjęcia aktorskie, zrobimy animację lalkową, malarską i rysunkową, również w stereo 3D. Nasz profesjonalizm w 2009 roku docenila Amerykanska Akademia Filmowa przyznając nam Oscara. Na laurach nie osiedliśmy... 
                <br />
                <span id="s1-span1"></span>
                Oferujemy realizację profesjonalnych filmów promocyjnych, teledysków i filmów reklamowych przeznaczonych do emisji telewizyjnej (zarówno w 2D jak i w 3D), kinowej (w tym w kinach 3D) oraz na ekranach smartfonów.
            </p>
        </div>
        <div id="bg5-3">
            <img src="images/slide3/title.png" alt="Oferta" id="s2-img1" />
            <div id="s2-div1">
                <p>Wśród  technik oferowanych przez BreakThru Films znajdują się:</p>
                <ul>
                    <li>konwersja obrazu 2D na  stereo 3D</li>
                    <li>realizacja obrazu w stereo 3D</li>
                    <li>animacja lalkowa (poklatkowa)</li>
                    <li>animacja malarska (poklatkowa)</li>
                    <li>animacja CG (animacja komputerowa)</li>
                    <li>animacja rysunkowa</li>
                    <li>mieszane techniki animacji</li>
                    <li>łączenie animacji i zdjęć aktorskich</li>
                    <li>animacja obrazu w  2D  i stereo 3D</li>
                </ul>
            </div>
        </div>
        
        <div id="bg5-4">
            <div id="s4-div3">
                <a href="#" id="s4-arrow-left" class="s4-arrows"></a>
                <a href="#" id="s4-arrow-right" class="s4-arrows"></a>
                
                <?$page = 0; $counter=0; foreach($realizacje as $r):?>
                    
                    <?if($counter%8==0): $page++;?>
                        <div id="s4-films-page<?=$page?>" class="s4-films" <?if($counter==0):?> style="display: block;"<?endif;?>>
                    <?endif;?>
                
                        
                    <div class="s4-film">
                        
                        <?if(!empty($r['gallery'])):?>
                            <?$counter2=0; foreach($r['gallery'] as $g):?>
                                <?if($counter2==0):?>
                                    <img src="images/realizacje/<?=$g['id']?>_m.jpg" alt="" />
                                    <a href="images/realizacje/<?=$g['id']?>.jpg" rel="galeria" class="s4-film-inner s4-film-fancybox" title="<?=htmlspecialchars($r['tytul_'.LANG])?>">
                                        <span><?=$r['tytul_'.LANG]?>, </span><br /><br />
                                        <?=$r['rezyseria_'.LANG]?>
                                    </a>
                                <?else:?>
                                    <a href="images/realizacje/<?=$g['id']?>.jpg" rel="galeria" class="s4-film-fancybox hidden" title="<?=htmlspecialchars($r['tytul_'.LANG])?>"></a>
                                <?endif;?>
                            <?$counter2++; endforeach;?>    
                        <?else:?>
                            <img src="images/slide4/film-blank.jpg" alt="" />
                            <a class="s4-film-inner">
                                <span><?=$r['tytul_'.LANG]?>, </span><br /><br />
                                <?=$r['rezyseria']?>
                            </a>
                        <?endif;?>
                    </div>
                
                    <?if($counter%8==7):?>
                        </div>
                    <?endif;?>
                <?$counter++; endforeach;?>
            
                <?$counter--; if($counter%8!=7):?>
                    <?for(;$counter%8!=7;$counter++):?>
                        <div class="s4-film">
                            <img src="images/slide4/film-blank.jpg" alt="" />
                        </div>
                    <?endfor;?>
                    </div>
                <?endif;?>
            </div>    
                
            <div id="realizacje-pages-counter" style="display: none;"><?=$page?></div>
            
            
            <div id="s4-films-bottom"></div>
        </div>
        
        <div id="bg5-5">
<!--            <img src="images/slide5/player.gif" alt="" id="s5-img1" />-->
            
            <div id="s5-div1">
                <div id="s5-div1-left">
                    <span>Showreel</span> <br /><br />
                    W naszych produkcjach łączymy różne techniki filmowe; mamy doświadczenie zarówno w produkcjach 3D jak i 2D, animacji połączonej ze zdjęciami aktorskimi,
                    animacji lalkowej, malarskiej, CG oraz rysunkowej, efektach specjalnych zarówno w 2D jak<br /> i stereo 3D. <br /><br />

                    Zapraszamy do obejrzenia kolażu filmów animowanych zrealizowanych przez Breakthru. Obraz dostępny jest także<br /> w stereo 3D.

                    <a href="#" id="s5-a1"><img src="images/slide5/odtworz-3d.gif" alt="" /></a>
                </div>
                <div id="s5-div1-right">
                    <video id="my_video_1" class="video-js vjs-default-skin" controls preload="auto" width="564" height="374" poster="images/slide5/showreal-2d.jpg" data-setup="{}">
                        <source src="videos/1.mp4" type='video/mp4'>
                    </video>
                    
                    <video id="my_video_2" class="video-js vjs-default-skin" controls preload="auto" width="564" height="374" poster="images/slide5/showreal-3d.jpg" data-setup="{}">
                        <source src="videos/2.mp4" type='video/mp4'>
                    </video>             
                    
                    <video id="my_video_3" class="video-js vjs-default-skin" controls preload="auto" width="564" height="374" poster="images/slide5/video.jpg" data-setup="{}">
                        <source src="http://video-js.zencoder.com/oceans-clip.mp4" type='video/mp4'>
                        <source src="http://video-js.zencoder.com/oceans-clip.webm" type='video/webm'>
                    </video>
                </div>
                <div id="s5-div1-bottom"></div>
                <ul id="s5-ul1">
                    <li><a id="s5-ul1-a1" href="#" class="active">1</a></li>
                    <li><a id="s5-ul1-a2" href="#">2</a></li> 
                </ul>
            </div>
        </div>        
        
<!--        <div id="bg5-3">
            <img src="images/slide3/bgr.png" alt="" id="s3-img1" />
        </div>-->

    </div>        
        
    <!-- Speed 4 left -->
    <div id="parallax-bg4">
        <img id="bg4-1" src="images/slide1/str-glowna-4.png" alt=""/>
        <img id="bg4-3" src="images/slide2/tech-4.png" alt=""/>
        <img id="bg4-6" src="images/slide6/slice-4.png" alt=""/>
    </div>        
        
        
    <!-- Speed 3 left -->
    <div id="parallax-bg3">
        <img id="bg3-1" src="images/slide1/str-glowna-3.png" alt=""/>
        <img id="bg3-2" src="images/slide2/zespol-3.png" alt=""/>
        <img id="bg3-3" src="images/slide2/tech-3.png" alt=""/>
        <img id="bg3-6" src="images/slide6/slice-3.png" alt=""/>
    </div>

    <!-- Speed 2 left -->
    <div id="parallax-bg2">
        <img id="bg2-1" src="images/slide1/str-glowna-2.png" alt=""/>
        <img id="bg2-2" src="images/slide2/zespol-2.png" alt=""/>
        <img id="bg2-3" src="images/slide2/tech-2.png" alt=""/>
        <img id="bg2-6" src="images/slide6/slice-2.png" alt=""/>
    </div>

    <!-- Speed 1 left -->
    <div id="parallax-bg1">
        <img id="bg1-1" src="images/slide1/str-glowna-1.png" alt=""/>
        <img id="bg1-2" src="images/slide2/zespol-1.png" alt=""/>
        <img id="bg1-3" src="images/slide2/tech-1.png" alt=""/>
        <img id="bg1-4" src="images/slide4/ptak.png" alt=""/>
        <img id="bg1-5" src="images/slide4/ptak.png" alt=""/>
        <img id="bg1-6" src="images/slide6/slice-1.png" alt=""/>
    </div>
        
        
        <div id="slide1">
            <div id="slide1-before"></div>
            <div id="slide1-pos"></div>
            <img src="images/slide1/postacie.png" alt="" id="s1-img2" />
        </div>
        <div id="slide2">
            <div id="slide2-pos"></div>
            <img src="images/slide2/postacie.png" alt="" id="s2-img2" />
        </div>
        <div id="slide3">
            <div id="slide3-pos"></div>
        </div>
        <div id="slide4">
            <div id="slide4-pos"></div>
            <img src="images/slide4/postacie.png" alt="" id="s4-img1" />
            <div id="s4-div1">
                <img src="images/slide4/title.png" alt="O Nas" id="s4-img2" />       
                <div id="s4-div2"></div>
                <p>Powstaliśmy w 2003 roku w Londynie. Jesteśmy dynamicznym zespołem artystyczno-produkcyjnym, <br />w skład którego wchodzą reżyserzy, producenci, animatorzy, graficy komputerowi, specjaliści od stereoskopii i obróbki obrazu. Współpracujemy z  twórcami z całego świata, co gwarantuje świeże spojrzenie i niewyczerpaną bazę nowatorskich rozwiazań technologicznych. </p>
                <br />
                <p>Podążamy za najnowszymi trendami i współkreujemy je. Jako jedyni w Polsce zrealizowaliśmy 7 filmów animowanych w technice stereo 3D. Nasze produkcje zostały nagrodzone podczas prestiżowych festiwali obraz stereoskopowego w  Los Angeles w ramach 3D LA Film Festival, a także 3D Stereo MEDIA 2011 w belgijskim Liege.</p>
                <a href="#" id="s4-prev"></a>
                <a href="#" id="s4-next"></a>
            </div>
        </div>
        
        <div id="slide5">
            <div id="slide5-pos"></div>
            <img src="images/slide5/bgr.png" alt="" id="s5-img2" />
        </div>
        <div id="slide6">
            <div id="slide6-pos"></div>
            <div id="slide6-pos-after"></div>
        </div>
        
    </div>
    <div id="bottom">
        <div id="bottom-trans">
            <ul id="socials">
                <li id="li-youtube"><a target="_blank" href="http://www.youtube.com/user/BreakThruPoland?feature=watch">YouTube</a></li>
                <li id="li-facebook"><a href="http://www.facebook.com/pages/BreakThru-Films/139511119775?ref=ts">Facebook</a></li>
                <li id="li-vimeo"><a target="_blank" href="http://vimeo.com/breakthrustudios">Vimeo</a></li>
                <li id="li-twitter"><a target="_blank" href="https://twitter.com/breakthrufilms">Twitter</a></li>
            </ul>
            <ul id="menu-bottom-en">
                <li id="li-strefa"><a target="_blank" href="http://klient.breakthrustudios.pl">Strefa Klienta</a></li>
                <li id="li-kontakt"><a href="#" class="a-skontaktuj-sie">Skontaktuj się z Nami</a></li>
            </ul>
        </div>
        <div id="bottom-inner-en">
            
            
            <div id="div-bi-email">email: <a href="mailto:office@breakthrustudios.pl">Office@breakthrustudios.pl</a></div>
            <div id="div-bi-telefon">
                telefon: +48 668 685 415 <br />
                <span style="margin-left: 55px;">+48 696 839 939</span>
            </div>
            
            <div id="map_canvas"></div>
	
            <div id="div-bi-formularz">
                <form method="post" id="form-kontakt" action="_kontakt.php">
                    <dl>
                        <dt>imię, nazwisko</dt>	<dd><input type="text" name="name" value="" class="input-text" /></dd>
                        <dt>e-mail</dt>   <dd><input type="text" name="email" value="" class="input-text" id="input-email" /></dd>
                        <dt>treść wiadomości</dt>	
                        <dd>
                            <textarea name="content" id="textarea-content"></textarea>
                        </dd>
                        <dt>tekst z obrazka</dt>      
                        <dd style="text-align: left; width: 186px;">
                            <input type="text" name="captcha" value=""  id="input-captcha" class="input-text-short" style="float: left;" />
                            <img src="images/captcha/dc1d7b5030e8bb357ee5c13b729046e3.jpg" alt="" id="img-captcha" />
                        </dd>
                        <div class="clear"></div>
                        <dt id="dt-error"></dt>
                        <dd id="dd-zapisz">
                            <input type="submit" id="input-zapisz" />
                        </dd>
                    </dl>
                </form>
                <div class="clear"></div>
            </div>
            
            <div id="div-bi-sent">
                Wiadomość została wysłana!
            </div>
            
        </div>
        <div id="bottom-black">
            <div id="bottom-black-inner">
                <span id="span-copyright">
                    Copyright © 2012  BreakthruStudios
                </span>
            </div>
        </div>
    </div>
</body>
</html>